spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9898
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

server:
  port: 9901
